### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by blasco** [lambdalisue/vim-operator-breakline#1]
Do you have a working version of this plugin? I like the idea.

**Comment by lambdalisue** [comment]
Fixed. Try again with the latest master (don't forge to install kana/vim-operator-user).

**Comment by blasco** [comment]
Hi there. Still not working, I have kana/vim-operator-user installed. The plugin says: 
```
E486: Pattern not found: .\{80}\zs
```

Seems there is something wrong with the reg expression. Any idea?

**Comment by blasco** [comment]
The manual version seems to be working, although after the operation the cursor is kept in visual mode selecting the text, I think we should return to normal mode after the operation:

![Screenshot_2019-10-04_12-04-52](https://user-images.githubusercontent.com/3214400/66199591-3ed75a00-e69f-11e9-970a-2c35cfd737aa.png)
![Screenshot_2019-10-04_12-05-07](https://user-images.githubusercontent.com/3214400/66199607-439c0e00-e69f-11e9-9425-5df05233f712.png)

An additional unrelated idea, we could also set the default to 80, but not put it in the input, so if we want to change it we don't need to delete two characters:
"Please input the number of characters allowed in a single line (default=80): "
if empty, then the default is used.

**Comment by lambdalisue** [comment]
I'm working on it.

> E486: Pattern not found: .\{80}\zs

It **was** showed when the target text is shorter than 80 characters. Now it silently fails in that situation.

> An additional unrelated idea, we could also set the default to 80, but not put it in the input, so if we want to change it we don't need to delete two characters:
"Please input the number of characters allowed in a single line (default=80): "
if empty, then the default is used.

It's a bit tricky to detect if a user hit `Escape` or just hit `Enter` without value in Vim.
While this plugin is quite small and simple, I'd rather keep the current behavior than introducing complexity.

**Comment by lambdalisue** [comment]
Fixed. Could you try the latest master?

**Comment by blasco** [comment]
Now it works great!
